spring.application.name=liderum-notification-service
server.port=${PORT:8081}

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

liderum.rabbitmq.exchange=${LIDERUM_RABBITMQ_EXCHANGE:liderum.events}
liderum.rabbitmq.guild-event-created-routing-key=${LIDERUM_RABBITMQ_GUILD_EVENT_CREATED_ROUTING_KEY:guild.event.created}
liderum.rabbitmq.guild-event-created-queue=${LIDERUM_RABBITMQ_GUILD_EVENT_CREATED_QUEUE:notification.guild-event-created}
