CREATE TABLE guilds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    server_name VARCHAR(255)
);

CREATE TABLE member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classe VARCHAR(255),
    guild_role VARCHAR(255),
    nickname VARCHAR(255),
    phone VARCHAR(255),
    rank VARCHAR(255),
 guild_id BIGINT NOT NULL,
    team_id BIGINT
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    guild_role VARCHAR(255),
    guild_id BIGINT,
    member_id BIGINT,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255),
    guild_id BIGINT NOT NULL,
    leader_id BIGINT
);

CREATE TABLE event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    date TIMESTAMP,
    description VARCHAR(255),
    guild_id BIGINT NOT NULL
);

CREATE TABLE attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    status VARCHAR(255)
);

ALTER TABLE users
    ADD CONSTRAINT fk_users_guild FOREIGN KEY (guild_id) REFERENCES guilds (id);
ALTER TABLE users
    ADD CONSTRAINT fk_users_member FOREIGN KEY (member_id) REFERENCES member (id);
ALTER TABLE member
    ADD CONSTRAINT fk_member_guild FOREIGN KEY (guild_id) REFERENCES guilds (id);
ALTER TABLE member
    ADD CONSTRAINT fk_member_team FOREIGN KEY (team_id) REFERENCES team (id);
ALTER TABLE team
    ADD CONSTRAINT fk_team_guild FOREIGN KEY (guild_id) REFERENCES guilds (id);
ALTER TABLE team
    ADD CONSTRAINT fk_team_leader FOREIGN KEY (leader_id) REFERENCES users (id);
ALTER TABLE event
    ADD CONSTRAINT fk_event_guild FOREIGN KEY (guild_id) REFERENCES guilds (id);
ALTER TABLE attendance
    ADD CONSTRAINT fk_attendance_member FOREIGN KEY (member_id) REFERENCES member (id);
ALTER TABLE attendance
    ADD CONSTRAINT fk_attendance_event FOREIGN KEY (event_id) REFERENCES event (id);

CREATE INDEX idx_users_guild ON users (guild_id);
CREATE INDEX idx_users_guild_role ON users (guild_id, guild_role);
CREATE INDEX idx_member_guild ON member (guild_id);
CREATE INDEX idx_team_guild ON team (guild_id);
CREATE INDEX idx_event_guild ON event (guild_id);
CREATE INDEX idx_attendance_member ON attendance (member_id);
CREATE INDEX idx_attendance_event ON attendance (event_id);
