package com.example.Liderum.Services.Impl;
import com.example.Liderum.Entities.*; import com.example.Liderum.Enums.UserStatus; import com.example.Liderum.Repository.UserActivationTokenRepository; import com.example.Liderum.Services.UserActivationService; import com.example.Liderum.dto.*; import lombok.RequiredArgsConstructor; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.util.Base64; import java.util.HexFormat;
@Service @RequiredArgsConstructor public class UserActivationServiceImpl implements UserActivationService {
 private static final Duration VALIDITY=Duration.ofHours(24); private final UserActivationTokenRepository repo; private final PasswordEncoder encoder; private final SecureRandom random=new SecureRandom();
 @Override @Transactional public UserActivationResponseDTO createActivation(User user){repo.findAllByUserIdAndUsedAtIsNullAndRevokedAtIsNull(user.getId()).forEach(t -> t.setRevokedAt(Instant.now())); byte[] b=new byte[32]; random.nextBytes(b); String raw=Base64.getUrlEncoder().withoutPadding().encodeToString(b); UserActivationToken t=new UserActivationToken(); t.setUser(user); t.setTokenHash(hash(raw)); t.setExpiresAt(Instant.now().plus(VALIDITY)); repo.save(t); return new UserActivationResponseDTO(dto(user),raw);}
 @Override @Transactional public void activate(ActivationRequestDTO r){ UserActivationToken t=repo.findByTokenHash(hash(r.getToken())).orElseThrow(()->new IllegalArgumentException("Invalid activation token")); Instant now=Instant.now(); if(t.getUsedAt()!=null||t.getRevokedAt()!=null||t.getExpiresAt().isBefore(now)||t.getUser().getStatus()!=UserStatus.PENDING) throw new IllegalArgumentException("Invalid activation token"); User u=t.getUser(); u.setPassword(encoder.encode(r.getPassword())); u.setStatus(UserStatus.ACTIVE); t.setUsedAt(now); }
 private String hash(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 private UserResponseDTO dto(User u){UserResponseDTO d=new UserResponseDTO(); d.setId(u.getId()); d.setUsername(u.getUsername()); d.setEmail(u.getEmail()); d.setGuildRole(u.getGuildRole()); d.setStatus(u.getStatus()); return d;}
}
